spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?autoReconnect=true
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    username: root
    password: root
server:
  port: 8081