spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
server:
  port: 8081