spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti6ui?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
server:
  port: 8081
  context-path: /api